### ISSUE TITLE
clone해서 실행하려하니 Xcode run할때 에러 (tidev/iOS/main.jsbundle: No such file or directory)

### ISSUE THREAD

**Issue by yomybaby** [taggon/tidev#2]
더 해줘야하는 내용이 있나요?^^

**Comment by taggon** [comment]
다시 받으시면 수정되어 있을 것입니다.
제가 배포하려고 AppDelegate.m 파일의 OPTION 2를 활성화해두었는데 그걸 그대로 올려서 발생한 문제입니다. 개발할 때는 OPTION 1을 사용해야 하거든요. 지금은 0c4f6dbac86838cd3230c9958041b2127b6a6f41 에서 수정되었습니다.
